### ISSUE TITLE
Поддержка нескольких чатов

### ISSUE THREAD

**Issue by nm17** [rgit/CheckYourStats#1]
В базе уже храниться `chat_id`, осталось убрать ограничение чата и добавить ограничение графиков в минуту.

**Comment by feschenko** [comment]
Проверь https://github.com/rgit/CheckYourStats/tree/dev-stats.

**Comment by feschenko** [comment]
Please make another issue with **limiting of a chart per minute**, because the bot already supports work in more than one chat.
